query MetaEntities {
  metaEntities {
    guid
    displayName
  }
}

query MetaEntity($guid: String!) {
  metaEntity(guid: $guid) {
    guid
    displayName
  }
}

mutation CreateMetaEntity($dto: CreateMetaEntityDto!) {
  createMetaEntity(createMetaEntityDto: $dto) {
    guid
  }
}

mutation UpdateMetaEntity($dto: UpdateMetaEntityDto!) {
  updateMetaEntity(updateMetaEntityDto: $dto) {
    guid
  }
}
